options:
  release-mode: false
  fix-move-keys: true
  language: en-us
  majar-version: 0
  minor-version: 1
  patch-version: 1
release-datetime:
  release_year: 2021  # 年
  release_month: 12  # 月份
  release_day: 26  # 天
  release_hour: 21  # 小时
  release_min: 11  # 分钟
  release_sec: 10  # 秒
